// import type { MenuData } from '~@/layouts/basic-layout/typing'

export function getRouteMenusApi() {
  // Where you define which of the menus in Servers\routes\menu\index.ts are accessible by the user
  // return useGet<MenuData>('/menu')
  return {
    data: [
      // {
      //   id: 2,
      //   parentId: null,
      //   title: '分析页',
      //   icon: 'DashboardOutlined',
      //   component: '/dashboard/analysis',
      //   path: '/dashboard/analysis',
      //   name: 'DashboardAnalysis',
      //   keepAlive: true,
      //   locale: 'menu.dashboard.analysis',
      // },
      // {
      //   id: 1,
      //   parentId: null,
      //   title: '仪表盘',
      //   icon: 'DashboardOutlined',
      //   component: 'RouteView',
      //   redirect: '/dashboard/analysis',
      //   path: '/dashboard',
      //   name: 'Dashboard',
      //   locale: 'menu.dashboard',
      // },
      // {
      //   id: 17,
      //   parentId: null,
      //   title: '工作台',
      //   component: '/dashboard/workplace',
      //   path: '/dashboard/workplace',
      //   name: 'DashboardWorkplace',
      //   keepAlive: true,
      //   locale: 'menu.dashboard.workplace',
      // },
      {
        id: 3,
        parentId: null,
        title: 'My Class',
        icon: 'FormOutlined',
        component: 'RouteView',
        redirect: '/my-class/2025-2026/1st',
        path: '/my-class',
        name: 'My Class',
        locale: 'menu.my-class',
      },
      {
        id: 4,
        parentId: 3,
        title: 'AY 2025-2026',
        icon: 'FormOutlined',
        component: 'RouteView',
        redirect: '/my-class/2025-2026/1st',
        path: '/my-class',
        name: 'AY20252026',
        locale: 'AY 2025-2026',
      },
      {
        id: 5,
        parentId: 4,
        title: '1st Semester',
        component: '/my-class/index',
        path: '/my-class/2025-2026/1st',
        name: 'AY202520261ST',
        keepAlive: false,
        locale: '1st Semester',
      },
      {
        id: 17,
        parentId: null,
        title: 'ITE 101 - I-EEd3',
        hideInMenu: true,
        icon: 'DashboardOutlined',
        component: '/my-class/ClassPage',
        path: '/my-class/2025-2026/1st/ite101/i-eed3',
        name: 'ITE101I-EEd3',
        keepAlive: false,
        locale: 'ITE 101 - I-EEd3',
      },
      {
        id: 6,
        parentId: 3,
        title: 'AY 2024-2025',
        icon: 'FormOutlined',
        component: 'RouteView',
        redirect: '/my-class/2024-2025/1st',
        path: '/my-class',
        name: 'AY20242025',
        locale: 'AY 2024-2025',
      },
      {
        id: 7,
        parentId: 6,
        title: '1st Semester',
        component: '/my-class/index',
        path: '/my-class/2024-2025/1st',
        name: 'AY202420251ST',
        keepAlive: false,
        locale: '1st Semester',
      },
      {
        id: 8,
        parentId: 6,
        title: '2nd Semester',
        component: '/my-class/index',
        path: '/my-class/2024-2025/2nd',
        name: 'AY202420252ND',
        keepAlive: false,
        locale: '2nd Semester',
      },
      {
        id: 14,
        parentId: null,
        title: 'Activities',
        icon: 'FormOutlined',
        component: 'RouteView',
        redirect: '/quiz-maker',
        path: '/activities',
        name: 'Activities',
        locale: 'Activities',
      },
      {
        id: 9,
        parentId: 14,
        title: 'Quiz Maker',
        icon: 'DashboardOutlined',
        component: '/quiz-maker/index',
        path: '/quiz-maker',
        name: 'Quizmaker',
        keepAlive: false,
        locale: 'Quiz Maker',
      },
      {
        id: 10,
        parentId: 14,
        title: 'Test Maker',
        icon: 'DashboardOutlined',
        component: '/test-maker/index',
        path: '/test-maker',
        name: 'Testmaker',
        keepAlive: false,
        locale: 'Test Maker',
      },
      {
        id: 11,
        parentId: 14,
        title: 'Shared Tests and Quizzes',
        icon: 'DashboardOutlined',
        component: '/shared/index',
        path: '/shared-tests',
        name: 'SharedTests',
        keepAlive: false,
        locale: 'Shared Tests',
      },
      {
        id: 12,
        parentId: null,
        title: 'Events Calendar',
        icon: 'DashboardOutlined',
        component: '/events-calendar/index',
        path: '/calendar',
        name: 'EventsCalendar',
        keepAlive: false,
        locale: 'Events Calendar',
      },
      {
        id: 15,
        parentId: null,
        title: 'Files',
        icon: 'FormOutlined',
        component: 'RouteView',
        redirect: '/files/my-files',
        path: '/files',
        name: 'Files',
        locale: 'Files',
      },
      {
        id: 13,
        parentId: 15,
        title: 'My Files',
        icon: 'DashboardOutlined',
        component: '/file-management/my-files',
        path: '/files/my-files',
        name: 'MyFiles',
        keepAlive: false,
        locale: 'My Files',
      },
      {
        id: 16,
        parentId: 15,
        title: 'Shared Files',
        icon: 'DashboardOutlined',
        component: '/file-management/shared-files',
        path: '/files/shared-files',
        name: 'SharedFiles',
        keepAlive: false,
        locale: 'Shared Files',
      },

      {
        id: 20,
        parentId: null,
        title: 'Class Scheduling',
        icon: 'DashboardOutlined',
        component: '/scheduler/calendar',
        path: '/class-scheduling',
        name: 'ClassScheduling',
        keepAlive: false,
        locale: 'Class Schedules',
      },
      {
        id: 21,
        parentId: null,
        hideInMenu: true,
        title: 'Class Scheduling : Timeslot',
        icon: 'DashboardOutlined',
        component: '/scheduler/timeslot',
        path: '/class-scheduling/timeslot/monday/8',
        name: 'TimeslotScheduling1',
        keepAlive: false,
        locale: 'Class Timeslot Schedules',
      },
      {
        id: 22,
        parentId: null,
        hideInMenu: true,
        title: 'Class Scheduling : Timeslot',
        icon: 'DashboardOutlined',
        component: '/scheduler/timeslot',
        path: '/class-scheduling/timeslot/tuesday/10',
        name: 'TimeslotScheduling2',
        keepAlive: false,
        locale: 'Class Timeslot Schedules',
      },
      {
        id: 19,
        parentId: null,
        title: 'Professors',
        icon: 'DashboardOutlined',
        component: '/professors/index',
        path: '/professors',
        name: 'ProfessorsSetup',
        keepAlive: false,
        locale: 'Professors',
      },
      {
        id: 23,
        parentId: null,
        title: 'Departments',
        icon: 'DashboardOutlined',
        component: '/departments/index',
        path: '/departments',
        name: 'DepartmentsSetup',
        keepAlive: false,
        locale: 'Departments',
      },
      {
        id: 24,
        parentId: null,
        title: 'Room Setup',
        icon: 'DashboardOutlined',
        component: '/rooms/index',
        path: '/rooms',
        name: 'RoomsSetup',
        keepAlive: false,
        locale: 'Rooms Setup',
      },
      {
        id: 25,
        parentId: null,
        title: 'Courses Setup',
        icon: 'DashboardOutlined',
        component: '/courses/index',
        path: '/courses',
        name: 'CourseSetup',
        keepAlive: false,
        locale: 'Courses Setup',
      },
      {
        id: 26,
        parentId: null,
        title: 'Sections Setup',
        icon: 'DashboardOutlined',
        component: '/sections/index',
        path: '/sections',
        name: 'SectionSetup',
        keepAlive: false,
        locale: 'Sections Setup',
      },
       {
        id: 27,
        parentId: null,
        title: 'Admin Setup',
        icon: 'DashboardOutlined',
        component: '/admin/index',
        path: '/admin',
        name: 'AdminSetup',
        keepAlive: false,
        locale: 'Admin Setup',
      },
       {
        id: 28,
        parentId: null,
        title: 'Students Setup',
        icon: 'DashboardOutlined',
        component: '/students/index',
        path: '/students',
        name: 'StudentSetup',
        keepAlive: false,
        locale: 'Student Setup',
      },
    ],
  }
}
